Modal enhancement
farmerconnect/farmerconnect-ui pull request #118
Opened 2021-11-19 18:51 UTC by wagner-schwertz-poatek

added: close button to modal component
added: smoother animations to modal component
added: ability trigger onClose on key press

Added navigation features as well as smoother animations (including animation when closing modal)

2021-11-22 12:47 UTC, jotape-poatek submitted a review, later dismissed

2021-12-16 08:36 UTC, gateixeira requested changes
Please check the versioning

2021-12-16 08:36 UTC, gateixeira commented on CHANGELOG.md
> +## [3.0.1] 2021-12-15
I think this should be a minor instead of a patch, provided it's an enhancement rather than a fix.

2021-12-16 08:36 UTC, gateixeira commented on package.json
> +  "version": "3.0.1",
3.1.0

2021-12-16 11:29 UTC, tiagoalmeidadarosa submitted a review, later dismissed

2022-01-22 16:43 UTC, closed without merging

2022-01-22 16:44 UTC, wagner-schwertz-poatek commented
the changes in this PR are not suited for the current direction of the Modal component